package com.eatzy.flash.processor;

public enum ProcessorType {
    PROCESSOR_TYPE_CART_INFO,
    PROCESSOR_TYPE_FETCH_FILTER_BASED_OUTLET,
    PROCESSOR_TYPE_FETCH_NEW_ORDER,
    PROCESSOR_TYPE_FETCH_ORDER_UPDATE,
    PROCESSOR_TYPE_MENU_CARD_PROCESSOR,
    PROCESSOR_TYPE_ORDER_HISTORY_PROCESSOR,
    PROCESSOR_TYPE_ORDER_PROCESSOR,
    PROCESSOR_TYPE_POST_ORDER_UPDATE_PROCESSOR,
}
