package com.eatzy.flash.model.menu;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import static com.eatzy.flash.model.Constants.TABLE_NAME_MENU_DETAILS;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = TABLE_NAME_MENU_DETAILS)
public class MenuDDBRecord {

    public static final String ID= "id";
    public static final String MENU_ID = "menuID";
    public static final String MENU_NAME = "menuName";
    public static final String MENU_PRICE = "menuP";
    public static final String MENU_DESCRIPTION = "menuD";
    public static final String MENU_IMAGE_URI = "menuI";
    public static final String MENU_CATEGORY_COURSES = "categoryByC";
    public static final String MENU_CATEGORY_ETA = "categoryByETA";
    public static final String MENU_CATEGORY_REGION = "categoryByRegion";
    public static final String MENU_CATEGORY_MEAL = "categoryByMeal";

    public static final String SECONDARY_INDEX_NAME = "menuID-index";

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = ID)
    private String id;

    @DynamoDBAttribute(attributeName = MENU_ID)
    private String menuId;

    @DynamoDBAttribute(attributeName = MENU_NAME)
    private String getMenuName;
    @DynamoDBAttribute(attributeName = MENU_PRICE)
    private String getMenuPrice;
    @DynamoDBAttribute(attributeName = MENU_DESCRIPTION)
    private String getMenuDescription;
    @DynamoDBAttribute(attributeName = MENU_IMAGE_URI)
    private String getMenuImageUri;
    @DynamoDBAttribute(attributeName = MENU_CATEGORY_COURSES)
    private String getMenuCategoryCourses;
    @DynamoDBAttribute(attributeName = MENU_CATEGORY_ETA)
    private String getMenuCategoryEta;
    @DynamoDBAttribute(attributeName = MENU_CATEGORY_REGION)
    private String getMenuCategoryRegion;
    @DynamoDBAttribute(attributeName = MENU_CATEGORY_MEAL)
    private String getMenuCategoryMeal;

}


